//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ConstVal.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class ConstValParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		CONST=1, VAL=2, INTKW=3, ASSIGN=4, SEMI=5, COLON=6, ID=7, NUMBER=8, WS=9, 
		ERROR_CHAR=10;
	public const int
		RULE_start = 0;
	public static readonly string[] ruleNames = {
		"start"
	};

	private static readonly string[] _LiteralNames = {
		null, "'const'", "'val'", "'Int'", "'='", "';'", "':'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "CONST", "VAL", "INTKW", "ASSIGN", "SEMI", "COLON", "ID", "NUMBER", 
		"WS", "ERROR_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ConstVal.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static ConstValParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ConstValParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ConstValParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class StartContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(ConstValParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] CONST() { return GetTokens(ConstValParser.CONST); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONST(int i) {
			return GetToken(ConstValParser.CONST, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] VAL() { return GetTokens(ConstValParser.VAL); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VAL(int i) {
			return GetToken(ConstValParser.VAL, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(ConstValParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(ConstValParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COLON() { return GetTokens(ConstValParser.COLON); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON(int i) {
			return GetToken(ConstValParser.COLON, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] INTKW() { return GetTokens(ConstValParser.INTKW); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTKW(int i) {
			return GetToken(ConstValParser.INTKW, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ASSIGN() { return GetTokens(ConstValParser.ASSIGN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN(int i) {
			return GetToken(ConstValParser.ASSIGN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] NUMBER() { return GetTokens(ConstValParser.NUMBER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER(int i) {
			return GetToken(ConstValParser.NUMBER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SEMI() { return GetTokens(ConstValParser.SEMI); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI(int i) {
			return GetToken(ConstValParser.SEMI, i);
		}
		public StartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_start; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IConstValListener typedListener = listener as IConstValListener;
			if (typedListener != null) typedListener.EnterStart(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IConstValListener typedListener = listener as IConstValListener;
			if (typedListener != null) typedListener.ExitStart(this);
		}
	}

	[RuleVersion(0)]
	public StartContext start() {
		StartContext _localctx = new StartContext(Context, State);
		EnterRule(_localctx, 0, RULE_start);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 12;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==CONST) {
				{
				{
				State = 2;
				Match(CONST);
				State = 3;
				Match(VAL);
				State = 4;
				Match(ID);
				State = 5;
				Match(COLON);
				State = 6;
				Match(INTKW);
				State = 7;
				Match(ASSIGN);
				State = 8;
				Match(NUMBER);
				State = 9;
				Match(SEMI);
				}
				}
				State = 14;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 15;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,10,18,2,0,7,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,5,0,11,8,0,10,0,12,0,
		14,9,0,1,0,1,0,1,0,0,0,1,0,0,0,17,0,12,1,0,0,0,2,3,5,1,0,0,3,4,5,2,0,0,
		4,5,5,7,0,0,5,6,5,6,0,0,6,7,5,3,0,0,7,8,5,4,0,0,8,9,5,8,0,0,9,11,5,5,0,
		0,10,2,1,0,0,0,11,14,1,0,0,0,12,10,1,0,0,0,12,13,1,0,0,0,13,15,1,0,0,0,
		14,12,1,0,0,0,15,16,5,0,0,1,16,1,1,0,0,0,1,12
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
