//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ConstVal.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class ConstValLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		CONST=1, VAL=2, INTKW=3, ASSIGN=4, SEMI=5, COLON=6, ID=7, NUMBER=8, WS=9, 
		ERROR_CHAR=10;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"CONST", "VAL", "INTKW", "ASSIGN", "SEMI", "COLON", "ID", "NUMBER", "LETTER", 
		"DIGIT", "NONZERO", "WS", "ERROR_CHAR"
	};


	public ConstValLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ConstValLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'const'", "'val'", "'Int'", "'='", "';'", "':'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "CONST", "VAL", "INTKW", "ASSIGN", "SEMI", "COLON", "ID", "NUMBER", 
		"WS", "ERROR_CHAR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "ConstVal.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static ConstValLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,10,92,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,1,0,1,0,1,0,1,0,
		1,0,1,0,1,1,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,3,1,3,1,4,1,4,1,5,1,5,1,6,1,
		6,3,6,50,8,6,1,6,1,6,1,6,5,6,55,8,6,10,6,12,6,58,9,6,1,7,1,7,1,7,5,7,63,
		8,7,10,7,12,7,66,9,7,1,7,1,7,5,7,70,8,7,10,7,12,7,73,9,7,1,7,3,7,76,8,
		7,1,8,1,8,1,9,1,9,1,10,1,10,1,11,4,11,85,8,11,11,11,12,11,86,1,11,1,11,
		1,12,1,12,0,0,13,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,0,19,0,21,0,23,
		9,25,10,1,0,4,2,0,65,90,97,122,1,0,48,57,1,0,49,57,3,0,9,10,13,13,32,32,
		97,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,
		0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,0,1,27,1,0,0,0,
		3,33,1,0,0,0,5,37,1,0,0,0,7,41,1,0,0,0,9,43,1,0,0,0,11,45,1,0,0,0,13,49,
		1,0,0,0,15,75,1,0,0,0,17,77,1,0,0,0,19,79,1,0,0,0,21,81,1,0,0,0,23,84,
		1,0,0,0,25,90,1,0,0,0,27,28,5,99,0,0,28,29,5,111,0,0,29,30,5,110,0,0,30,
		31,5,115,0,0,31,32,5,116,0,0,32,2,1,0,0,0,33,34,5,118,0,0,34,35,5,97,0,
		0,35,36,5,108,0,0,36,4,1,0,0,0,37,38,5,73,0,0,38,39,5,110,0,0,39,40,5,
		116,0,0,40,6,1,0,0,0,41,42,5,61,0,0,42,8,1,0,0,0,43,44,5,59,0,0,44,10,
		1,0,0,0,45,46,5,58,0,0,46,12,1,0,0,0,47,50,3,17,8,0,48,50,5,95,0,0,49,
		47,1,0,0,0,49,48,1,0,0,0,50,56,1,0,0,0,51,55,3,17,8,0,52,55,3,19,9,0,53,
		55,5,95,0,0,54,51,1,0,0,0,54,52,1,0,0,0,54,53,1,0,0,0,55,58,1,0,0,0,56,
		54,1,0,0,0,56,57,1,0,0,0,57,14,1,0,0,0,58,56,1,0,0,0,59,60,5,45,0,0,60,
		64,3,21,10,0,61,63,3,19,9,0,62,61,1,0,0,0,63,66,1,0,0,0,64,62,1,0,0,0,
		64,65,1,0,0,0,65,76,1,0,0,0,66,64,1,0,0,0,67,71,3,21,10,0,68,70,3,19,9,
		0,69,68,1,0,0,0,70,73,1,0,0,0,71,69,1,0,0,0,71,72,1,0,0,0,72,76,1,0,0,
		0,73,71,1,0,0,0,74,76,5,48,0,0,75,59,1,0,0,0,75,67,1,0,0,0,75,74,1,0,0,
		0,76,16,1,0,0,0,77,78,7,0,0,0,78,18,1,0,0,0,79,80,7,1,0,0,80,20,1,0,0,
		0,81,82,7,2,0,0,82,22,1,0,0,0,83,85,7,3,0,0,84,83,1,0,0,0,85,86,1,0,0,
		0,86,84,1,0,0,0,86,87,1,0,0,0,87,88,1,0,0,0,88,89,6,11,0,0,89,24,1,0,0,
		0,90,91,9,0,0,0,91,26,1,0,0,0,8,0,49,54,56,64,71,75,86,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
